# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Publish Package

on:
  release:
    types: [created]

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout develop branch
        uses: actions/checkout@v3
        with:
          ref: tags/${GITHUB_REF##*/}
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          registry-url: https://registry.npmjs.org/
      - name: Publish NPM
        run: |
          echo github.ref is ${{github.ref}}
          echo GITHUB_REF is ${GITHUB_REF}
          yarn --frozen-lockfile
          yarn build
          yarn test
          yarn publish --access public dist
        env:
          NODE_AUTH_TOKEN: ${{secrets.PUBLISH_CSS}}
