# This script requires a Personal access token to be created. The token
# should be added as a repository secret called "RELEASE_PLEASE" under
# https://github.com/OWNER/REPO/settings/secrets/actions
#
# The permissions required are:
#
# Creating a PAT with these permissions is not working correctly.
# * Actions (r)
# * Commit statuses (r)
# * Contents (rw)
# * Deployments (rw)
# * Metadata (r)
# * Pull Requests (rw)
# * Webhooks (r)
# * Workflows (rw)
# 
# Adding these worked
# * Administration (rw)
# * Commit Statuses (rw)
# * Discussions (rw)
# * Issues (rw)
# * Merge Queues (rw)
# * Repository announcement banners (rw)
# * Variables (r)

name: Release Please

on:
  push:
    branches:
      - main

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v3
        with:
          ref: main

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          registry-url: https://registry.npmjs.org/

      - name: Install npm packages
        run: yarn --frozen-lockfile

      - name: Build package
        run: yarn build

      - name: Test package
        run: yarn test

      - name: Release Please
        uses: google-github-actions/release-please-action@v3
        id: release
        with:
          command: manifest
          token: ${{secrets.RELEASE_PLEASE}}

      - name: Report ref
        if: ${{ steps.release.outputs.release_created }}
        run: echo ${{ steps.release.outputs.tag_name }}

      - name: Publish NPM
        if: ${{ steps.release.outputs.release_created }}
        run: yarn publish --access public dist
        env:
          NODE_AUTH_TOKEN: ${{secrets.PUBLISH_CSS}}
