# This script tests that the main branch builds correctly
# and passes the test suite.

name: Build & Test

on:
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v3
        with:
          ref: main

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          registry-url: https://registry.npmjs.org/

      - name: Install npm packages
        run: yarn --frozen-lockfile

      - name: Build package
        run: yarn build

      - name: Test package
        run: yarn test

